import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="min-h-dvh bg-zinc-200 text-zinc-950">
            <Header />
          <div className="mx-auto flex min-h-dvh w-full max-w[1100px] flex-col border-x border-zinc-300 bg-white">
            <main className="px-4 py-8">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
